spring:
  application:
    name: insurance-be

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  profiles:
    active: 'dev'

  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: 1e36f06cf5d90fe6e948b0e5263644be
  expiration: 86400000

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}

profile:
  service:
    url: ${PROFILE_SERVICE_URL:http://localhost:8082} 
    
accommodation:
  service:
    url: ${ACCOMMODATION_SERVICE_URL:http://localhost:8082}

flight:
  service:
    url: ${FLIGHT_SERVICE_URL:http://localhost:8083} 

rental:
  service:
    url: ${RENTAL_SERVICE_URL:http://localhost:8084} 
    
billing:
  service:
    url: ${BILLING_SERVICE_URL:http://localhost:8085}

insurance:
  api-key: ${INSURANCE_API_KEY:super-secret-key-123}
  